# Generated by Django 5.2 on 2025-04-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_details_completed_rentalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
